"""
Configuration management for AI Service
"""

import os
from pathlib import Path
from typing import Optional, Literal

# Base paths
BASE_DIR = Path(__file__).parent
PRETRAINED_DIR = BASE_DIR / "pretrained"
DATA_DIR = BASE_DIR / "data"


class Config:
    """Configuration class for AI Service"""
    
    # Environment
    ENVIRONMENT: str = os.getenv("ENVIRONMENT", "development")
    DEBUG: bool = ENVIRONMENT == "development"
    
    # Server configuration
    PORT: int = int(os.getenv("PORT", 8000))
    HOST: str = os.getenv("HOST", "0.0.0.0")
    
    # Logging
    LOG_LEVEL: str = os.getenv("LOG_LEVEL", "INFO")
    
    # Model configuration
    MODEL_PATH: str = os.getenv("MODEL_PATH", "models/anomaly_model.joblib")
    
    # Drift detection configuration
    DRIFT_WINDOW_SIZE: int = int(os.getenv("DRIFT_WINDOW_SIZE", "30"))
    DRIFT_THRESHOLD: float = float(os.getenv("DRIFT_THRESHOLD", "0.05"))
    
    # CORS configuration
    CORS_ORIGINS: list = os.getenv("CORS_ORIGINS", "*").split(",")
    
    # Health check configuration
    HEALTH_CHECK_INTERVAL: int = int(os.getenv("HEALTH_CHECK_INTERVAL", "30"))
    HEALTH_CHECK_TIMEOUT: int = int(os.getenv("HEALTH_CHECK_TIMEOUT", "10"))
    
    # ==========================================================================
    # Threshold Configuration
    # ==========================================================================
    # Mode: "literature", "pretrained", or "hybrid" (recommended)
    # - literature: Use CDC/WHO/AHA guidelines only
    # - pretrained: Use thresholds trained from public datasets
    # - hybrid: Use pretrained if available, fall back to literature
    THRESHOLD_MODE: Literal["literature", "pretrained", "hybrid"] = os.getenv(
        "THRESHOLD_MODE", "hybrid"
    )  # type: ignore
    
    # Path to pretrained population baselines (JSON file)
    # Generated by: python scripts/train_from_datasets.py
    PRETRAINED_BASELINES_PATH: str = os.getenv(
        "PRETRAINED_BASELINES_PATH",
        str(PRETRAINED_DIR / "baselines.json")
    )
    
    # Path to pretrained Isolation Forest model (PKL file)
    PRETRAINED_MODEL_PATH: str = os.getenv(
        "PRETRAINED_MODEL_PATH",
        str(PRETRAINED_DIR / "isolation_forest.pkl")
    )
    
    # Whether to fall back to literature baselines if pretrained not found
    FALLBACK_TO_LITERATURE: bool = os.getenv(
        "FALLBACK_TO_LITERATURE", "true"
    ).lower() in ("true", "1", "yes")
    
    # ==========================================================================
    # Dataset Training Configuration
    # ==========================================================================
    # Path to dataset files directory
    DATA_PATH: str = os.getenv("DATA_PATH", str(DATA_DIR))
    
    # Isolation Forest parameters
    ISOLATION_FOREST_CONTAMINATION: float = float(
        os.getenv("ISOLATION_FOREST_CONTAMINATION", "0.1")
    )
    ISOLATION_FOREST_N_ESTIMATORS: int = int(
        os.getenv("ISOLATION_FOREST_N_ESTIMATORS", "100")
    )
    
    # Threshold computation method: "iqr", "percentile", or "zscore"
    THRESHOLD_METHOD: str = os.getenv("THRESHOLD_METHOD", "iqr")
    
    @classmethod
    def is_production(cls) -> bool:
        """Check if running in production environment"""
        return cls.ENVIRONMENT == "production"
    
    @classmethod
    def is_development(cls) -> bool:
        """Check if running in development environment"""
        return cls.ENVIRONMENT == "development"
    
    @classmethod
    def get_cors_origins(cls) -> list:
        """Get CORS origins based on environment"""
        if cls.is_development():
            return ["*"]
        return cls.CORS_ORIGINS
    
    @classmethod
    def get_threshold_config(cls):
        """
        Get threshold configuration for adaptive_thresholds module.
        
        Returns a dict that can be passed to configure_thresholds().
        """
        return {
            'mode': cls.THRESHOLD_MODE,
            'pretrained_baselines_path': cls.PRETRAINED_BASELINES_PATH,
            'pretrained_model_path': cls.PRETRAINED_MODEL_PATH,
            'fallback_to_literature': cls.FALLBACK_TO_LITERATURE
        }
    
    @classmethod
    def has_pretrained_baselines(cls) -> bool:
        """Check if pretrained baselines file exists."""
        return Path(cls.PRETRAINED_BASELINES_PATH).exists()
    
    @classmethod
    def has_pretrained_model(cls) -> bool:
        """Check if pretrained model file exists."""
        return Path(cls.PRETRAINED_MODEL_PATH).exists()


# Global config instance
config = Config()


def get_config() -> Config:
    """Get the global config instance."""
    return config 